### PR TITLE
Added matched filter derivation and details

### PR DESCRIPTION
**Pull request by kboone**
I wrote up the derivation of the matched filter, and the implementation details. I'm not really sure how your readthedocs system works, but I copied the formatting of one of your other files so it should be pretty close to right. Let me know where this should go exactly.

### CODE REVIEW

**Comment by kbarbary** [comment]
Looks great at first glance via github. The docs are built using sphinx, and readthedocs just runs sphinx for you, so you should be able to verify that the docs build correctly locally: Install sphinx and run `make html` from the `docs` directory.

One thing you'll have to do is to add a link to this file from within the `index.rst` file so that sphinx knows how to link the files together. Just add `matchedfilter` on line 51 of that file.

We may want to reorganize the documentation text at some point, but this is a fine place for now.

**Comment by kboone** [comment]
Ok, I moved those docs to the detection.rst page which I think makes more sense than having a separate page... let me know what you think about that. Everything seems to compile and link right now.

**Comment by kbarbary** [comment]
Yeah I think this is a better place for it.

**Comment by kbarbary** [comment]
By the way, I'm still working on the refactor of the convolution code. As with all things C, it's taking me way longer than expected.

**Comment by kboone** [comment]
Ok. Let me know if I can help with anything.

**Comment by kboone** [comment]
You could just switch to C++ and use templates. I'm pretty sure that cython supports C++, which would make this all straightforward.

Also, I noticed that you have using a mask as a feature for sep v0.5. That is easily done with the matched filter - it treats zeros in the error array as a mask. For the case of no error array, make an error array that is 1 where you want the pixel included, and 0 where you don't want it included. With an error array, just set the errors to 0 where you want pixels masked out. You can replace 0 for a large number if you want, but that's a bit messy.

**Comment by kbarbary** [comment]
I agree that C++ would probably make some of this more straightforward. It would probably be a good move if one were to write SEP from scratch. However, there are a few reasons to stick with plain C, such as coherency of the codebase as a whole (most of which is legacy C-style), and simpler interop of the C library with other languages (e.g., Julia).

I arrived at a solution that uses a multi-line buffer of floats. The buffer manages converting lines from the image as needed. `convolve` and `matched_filter` are now just single functions that operate on these buffers. Seems to work well and it was a net decrease in lines of code. If you're interested, the code is in the `conv-refactor` branch and some relevant areas are:

- https://github.com/kbarbary/sep/blob/conv-refactor/src/extract.h#L61 `arraybuffer` struct.
- https://github.com/kbarbary/sep/blob/conv-refactor/src/extract.c#L60 `arraybuffer`-related functions.

The branch already passes the tests, but I'd like to see if I can clean up the meaning of the `cdscan`/`cdwscan` buffers a bit more before merging.

Regarding masks, yes there are work-arounds using the error array, but it would be nice to take a third array as a separate input, so that you don't have to edit the error array. Should be pretty easy to add using the `arraybuffer` interface.

**Comment by kboone** [comment]
Looks good!

**Pull request merged**
