### PR TITLE
Use const pointers in more places + MSVC fixes

### PR DESCRIPTION
**Pull request by RReverser**
This is a follow-up to #109.

Switching to const pointers in image structure, and throughout the
codebase with -Wcast-qual warning to ensure that const pointers
are indeed not mutated. Also removed casts from allocation function
results - they're not necessary on `void *` pointers to any others.

Using `const *` allows consumers to more easily reason about inputs /
outputs of the API and safely share data between invocations or threads.

In the process I also fixed few more obvious UB warnings from clang-tidy
where it complained about usage of uninitialised data, although few more remain.

Also included few fixes for MSVC that got broken in #109.

### CODE REVIEW

**Comment by RReverser** [comment]
@kbarbary After this, I'll have one more separate PR and probably will be done for now :)

**Comment by RReverser** [comment]
Actually... the other change is fairly independent from this one, I'll submit both in parallel to speed up reviews :)

**Comment by RReverser** [comment]
@kbarbary Uh... ping? :) (on this and other PRs)

**Comment by kbarbary** [comment]
Ooops, sorry for the delay. Would you be interested in having write privileges to this repo?

**Comment by RReverser** [comment]
> Ooops, sorry for the delay. Would you be interested in having write privileges to this repo?

I wouldn't mind, but I don't promise active maintenance efforts from my side :)

**Pull request merged**
