### PR TITLE
Implemented matched filter for sep.extract

### PR DESCRIPTION
**Pull request by kboone**
This takes noise into account, and handles edge effects gracefully.

### CODE REVIEW

**Comment by kbarbary** [comment]
I read this fairly carefully and it looks good. It could be a major selling point of SEP over SExtractor for people doing low-S/N detection on images with rapidly varying noise (e.g., HST combined images). Minimally, we need:

- test(s)
- give the matched filter formula in the `sep.extract` docstring.

Optionally, it would be good to have a long page of documentation deriving the matched filter. For the time being, this could just go in `docs/detection.rst`.

**Comment by kbarbary** [comment]
Longer term (after this is merged) I'd like to refactor the code a bit. It isn't your fault, but the way you had to write this to fit into the existing code is awkward. For example, `cdscan` has different meanings when `noise` is present or not. We could still calculate `cdscan` as the unweighted convolution, even when `noise` is present. Or we could just get rid of all the convolved statistics entirely and refactor the code a bit to just refer to calculating detection thresholds.

It would also be nice to find a way to avoid the x-macros for the convolve and matched filter functions. We could do this by allocating a bigger buffer of `double` that would hold multiple image and noise lines used in the convolution. E.g., for a 3x3 convolution kernel, the buffers would be 3 lines big. Then the convolution functions would only have to be defined for doubles. We would just have to be careful about efficiently copying the image line into the right place in the buffer on each line.

**Comment by kbarbary** [comment]
One more thing: to sell this, it would be nice to give a small example (with images) that shows a situation where this approach is advantageous. I'm thinking a very small image (10x10?) and noise array with a low-S/N point source embedded.

**Comment by kboone** [comment]
I wrote up a test on a small grid. I'm not sure how you want to put this in sep, so I put it on pastebin for now:

http://pastebin.com/hkRcFNz1

**Comment by kbarbary** [comment]
Can you add something (possibly that code snippet) to the `test.py` file? If you haven't used pytest before, you'll create a new function, such as `test_matched_filter()` that runs this code and makes an assertion.

**Comment by kboone** [comment]
I added this test in the last commit.

**Comment by kbarbary** [comment]
Yes yes yes.

**Comment by kboone** [comment]
I'm going to write up the derivation in markdown format to document everything.

**Comment by kbarbary** [comment]
Great. I'll think about refactoring to avoid all the x macros.

**Pull request merged**
