### PR TITLE
Adding the errors on the variances ERRX2, ERRY2, and ERRXY

### PR DESCRIPTION
**Pull request by cmccully**
This pull request should add the errors on the variances (which measure the shapes of the psfs). 

I think most of the code is pretty simple. There are two main gotchas that I discovered. The first is that if the object is blended, both the centroid and the variance (and therefore the error on the variance as well) are calculated with respect to the previous centroid. This was a little odd to me, but as long as that is the expected behavior then its fine. 

The second gotcha is that currently if no "error" is given,  the error on the variances return all NaNs. I think that is alright, but might be worth adding documentation somewhere. 

Thoughts?

### CODE REVIEW

**Comment by kbarbary** [comment]
Out of curiosity, did you match the code in SExtractor? And if so, what is the file/function in the SE code base?

SExtractor does some weird things in places that are almost certainly not optimal. However, my philosophy so far has been to aim for compatibility, even in such cases.

Would it be easy to make the variance errors 0 rather than NaN when no error array is given? This would be similar to what the aperture functions do. It doesn't matter too much though - either way, there should be documentation saying that the variance errors are only meaningful when an error array is supplied. It would 

The failing test should probably be changed. With these new parameters in the output, we no longer expect the result of `extract` with `err=ones_like(data)` to be the same as with no error. I recommend removing any `'err*'` fields from both results before doing the comparison. I wonder how it passed on AppVeyor.

**Comment by kbarbary** [comment]
Somewhat relatedly, we can add tests against SE results for the `x2`, `y2` `xy` parameters and these new parameters. I can do that in a separate PR though -- I should have already had the variance parameters tested!

**Comment by cmccully** [comment]
Sorry for the delay. The code is loosely based on analyse.cL#213-215. The normalization comes further down at line at 273.  I think the correct way to do things for the Nans is to follow the original SExtractor more closely and calculate the error on the fly like L199 in analyse.c (in the original code base).

**Comment by cmccully** [comment]
I added some tests of the variance. They seem to be fine. I am still playing with the errors. However, with the newest version of SExtractor 2.19.5, there is a single value of xwin that does not match the sep position. The offset is 0.3 pixels. Do you want to take a look at that @kbarbary? I don't think they should be related to my changes, but it could use a fresh set of eyes. 

Looking at the errors, we should use the same error calculations as the aperture photometry if the error parameter is not provided. Does that seem sensible?

**Comment by kbarbary** [comment]
Regarding the stray xwin/ywin value, its fine, but it would be good to make the tests pass.

The value occurs for a weird object, for which I already make a special exception in the tests for its Kron radius value (see [here](https://github.com/kbarbary/sep/blob/657dc286b16d3e4b27987abd9fae3719ba4816ba/test.py#L113-L120)). The behavior of SExtractor changed from v2.8.6 (which I used to generate `image.cat`) to v2.19.5 (which you used to generate a new `image.cat`). The older SExtractor (and the SEP code) give xwin/ywin identical to the input x/y. This makes sense given the input radius (`sig`) of 0.0.

Anyway, it would be good to add a hack (with a note) to the windowed position test, as I did for the Kron radius. Could just set `refobjs["xwin"][i] = refobjs["x"]` before the test, or something like that.

**Comment by kbarbary** [comment]
For the error calculation, do you mean only accounting for poisson noise if no error array is provided? Or do you mean reporting zero error?

**Comment by cmccully** [comment]
For the xwin/ywin tests, that's fine, I don't mind adding it to the test. However, would it be better to fix it in the long run? Should I open a separate issue?

For the error calculation, I was indeed thinking of adding the poisson noise if no error array is provided. That is closer to the sextractor behavior. I will look at implementing that today.

**Comment by kbarbary** [comment]
For xwin/ywin (and also the Kron radius), it would be nice to know what the difference from SExtractor is for this one object. For the Kron radius, I just gave up trying to track it down at some point.

At least `sep.winpos` is behaving according to its documentation for this object.

**Comment by cmccully** [comment]
I did also just notice that there is a second position that is off by 0.00385 which is larger than the tolerance in your test. Should I just up the tolerance on this one?

**Comment by kbarbary** [comment]
Yes, just up the tolerance.

**Comment by cmccully** [comment]
Sorry. That is 0.0385 in x and 0.0102 in y for index 53. The kron radius is again pretty small: 0.148.

**Comment by kbarbary** [comment]
I opened #40 about the windowed position discrepancies. For this PR, just increase tolerances for the windowed position tests, or even just disable the tests entirely. Just want to make sure the other tests pass.

**Comment by cmccully** [comment]
158.2 and 158.3 are failing, but the error output is not clear to me what the issue is. Do you want to take a look?

https://travis-ci.org/kbarbary/sep/builds/126728651

**Comment by kbarbary** [comment]
In [this line](https://github.com/kbarbary/sep/blob/master/ctest/compare.py#L43) change the `6` index to `12`. It should be the index of the `flux_auto` column in the reference catalog from SExtractor.

You should be able to run `make test` to see if this C test passes locally.

**Comment by cmccully** [comment]
Oh ok. That seems to have fixed it. Thanks. Looking at the errors on the second moments now.

**Comment by cmccully** [comment]
Though now appveyor is failing but only for python 3...

**Comment by kbarbary** [comment]
Appveyor failure looks unrelated.

It occurs to me that to add Poisson noise, we need to (optionally) pass a `gain` to `sep.extract`, no?

**Comment by cmccully** [comment]
I believe so. Isn't that required in extract if no error matrix is passed? In that case how is the threshold calculated? Is it considered an absolute number? Can you point me to that line of code. 

To follow the manual from sextractor, I would think that we would need access to the sky rms and the gain and the image values in analyse.c. The original code base has this "field" type that has some of this info.  The alternative is to do things after the fact in cython, but move away from the original code base (which would be easier). What are your thoughts?

Also what is the difference between value and cvalue? I couldn't figure it out.

**Comment by kbarbary** [comment]
`extract` doesn't currently use a gain. Previously, the error array was only ever used for computing a threshold, so no gain was required. If the error array is not given, the threshold is treated as absolute. Here's the section of C code where the threshold is set:

https://github.com/kbarbary/sep/blob/657dc286b16d3e4b27987abd9fae3719ba4816ba/src/extract.c#L232-L252

In `sep_extract()` in C, the gain is available through the first argument, `sep_image* image` (though in `sep.pyx` we need to add a `gain` parameter). In C, you can then add a `gain` parameter to the relevant function in `analyse` and pass `image->gain` to it from `sep_extract()`.

`cvalue` is the "convolved" pixel value when filtering is on. Otherwise it is just the same as `value`. Note that SExtractor uses "convolved" values in places where it seems wrong to do so (but I can't remember concrete examples at the moment.)

**Comment by cmccully** [comment]
Hmm. I will have to step away for bit soon (my wife is due any day now), so this may have to wait. 

My thought would be to pass in a proper variance to extract (and it can be used anywhere else in the same way) as that would require the fewest changes to the code. That variance could be populated as the variance if it is provided, the square of the error if that is provided, or do the poisson + sky rms + readnoise if neither of those are provided (which is what Sextractor does internally). Then we could just use the PIXTLIST(pixt, var) where ever we need the uncertainties. I think that would preserve the behavior of SExtactor (which we should for sure test against) without having too add to the code complexity of SEP too much. What do you think?

**Comment by kbarbary** [comment]
I finished this PR off on master. It seems to work!

**Comment by cmccully** [comment]
Great! Glad to hear it.

**Pull request merged**
