### PR TITLE
Added pointer to sep.set_extract_pixstack in pix buf exception.

### PR DESCRIPTION
**Pull request by kboone**

### CODE REVIEW

**Comment by kboone** [comment]
Looks like something failed... I noticed that I used spaces for tabs instead of hard tabs. I made a new commit with that fixed. Is that it?

**Comment by kbarbary** [comment]
Nah the failure was my fault in something I pushed directly to master earlier today. Should be all good now on master.

You should be using spaces for tabs.

**Comment by kboone** [comment]
extract.c has a lot of hard tabs...

**Comment by kbarbary** [comment]
Oh, yeah I meant in `sep.pyx`. My editor likes hard tabs for C source code though I guess.

**Pull request merged**
